python architectures/arch1_db_per_tenant/issue_1_connection_pool_exhaustion_before.py
python architectures/arch1_db_per_tenant/issue_1_connection_pool_exhaustion_after.py

python architectures/arch1_db_per_tenant/issue_2_connection_leak_before.py
python architectures/arch1_db_per_tenant/issue_2_connection_leak_after.py

python architectures/arch1_db_per_tenant/issue_3_migration_overhead_before.py
python architectures/arch1_db_per_tenant/issue_3_migration_overhead_after.py

python architectures/arch1_db_per_tenant/issue_4_credential_rotation_before.py
python architectures/arch1_db_per_tenant/issue_4_credential_rotation_after.py

python architectures/arch1_db_per_tenant/issue_5_routing_bypass_before.py
python architectures/arch1_db_per_tenant/issue_5_routing_bypass_after.py